### PR TITLE
removed save and load validators from store

### PR DESCRIPTION
**Pull request by chandiniv1**
closes: #1344 

## Summary by CodeRabbit

- **Refactor**
  - Streamlined the application by removing outdated validator set storage and retrieval functions.
  - Simplified codebase by eliminating unused global variables and parameters.
  - Enhanced system performance by decoupling from external `cmtypes` package dependencies.

- **Documentation**
  - Updated function naming for clarity, changing `GetState` to `LoadState`.

### CODE REVIEW

**Review by Manav-Aggarwal — APPROVED** [review]
Thanks, looks great! LGTM

**Comment by nashqueue** [comment]
CI breaks as the methods are still being used

**Comment by Manav-Aggarwal** [comment]
Need to resolve merge conflicts.

**Review by Manav-Aggarwal — CHANGES_REQUESTED** [review]
Need to resolve merge conflicts.

**Pull request merged**
