### PR TITLE
Refactor TestGetNodeHeight 

### PR DESCRIPTION
**Pull request by AryanGodara**
## Overview

I've refactored the testcases in `TestGetNodeHeight` into a struct-list format for a cleaner testing interface. And taken out the `SetDalc` pattern, repeated in the codes, out to a separate helper function.

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

## Summary by CodeRabbit

- **Refactor**
	- Improved the setup process for integration tests by introducing a centralized method for node creation and configuration.
	- Optimized test code by consolidating repetitive setup tasks and enhancing the clarity of height retrieval tests.

### CODE REVIEW

**Review by MSevey — CHANGES_REQUESTED** [review]
this PR still includes the commit which has the start stop logic changes. 
either we should mark this PR as draft and dependent on #1544 or we should remove that commit and just review the changes to `TestGetNodeHeight`

**Comment by AryanGodara** [comment]
> this PR still includes the commit which has the start stop logic changes. either we should mark this PR as draft and dependent on #1544 or we should remove that commit and just review the changes to `TestGetNodeHeight`

I created this branch on top of #1544 branch, to avoid rebase conflicts later on 😅 . Poor choice on my part. I'll remove that first commit, and push only relevant changes here.

**Review by MSevey — APPROVED** [review]

**Comment by MSevey** [comment]
> > this PR still includes the commit which has the start stop logic changes. either we should mark this PR as draft and dependent on #1544 or we should remove that commit and just review the changes to `TestGetNodeHeight`
> 
> I created this branch on top of #1544 branch, to avoid rebase conflicts later on 😅 . Poor choice on my part. I'll remove that first commit, and push only relevant changes here.

makes sense. since the changes can be pretty cleanly separated I don't suspect there to be much in terms of conflict. 
Also keeping them fully separate ends up being faster even with conflicts because you naturally bottleneck to the true constraint as opposed to the imposed constraint of whichever the first change is. 

looks good now!

**Comment by MSevey** [comment]
There might be an unrelated flaky test https://github.com/rollkit/rollkit/actions/runs/7891260736/job/21536776255?pr=1545#step:4:2712

cc @Manav-Aggarwal have we seen this one yet?

**Comment by Manav-Aggarwal** [comment]
> https://github.com/rollkit/rollkit/actions/runs/7891260736/job/21536776255?pr=1545#step:4:2712

This was a flaky test on main that was reverted: https://github.com/rollkit/rollkit/pull/1521, so rebasing should fix it.

**Review by Manav-Aggarwal — APPROVED** [review]

**Pull request merged**
