### PR TITLE
Update readme and add tendermint types.pb.go  to gitignore

### PR DESCRIPTION
**Pull request by nashqueue**
Fixes: #730

### CODE REVIEW

**Comment by gupadhyaya** [comment]
@nashqueue i don't think we need to add the tendermint types pb file to the repo.

**Comment by nashqueue** [comment]
Do you think we should then put it in the .gitignore ?

**Comment by gupadhyaya** [comment]
@nashqueue can we close this PR? as it is not needed.

**Review by tuxcanfly — APPROVED** [review]
OK.

**Review by gupadhyaya — APPROVED** [review]

**Pull request merged**
