### PR TITLE
chore: update CLI docs description

### PR DESCRIPTION
**Pull request by Manav-Aggarwal**
## Overview
Update CLI docs description

## Summary by CodeRabbit

- **Documentation**
  - Updated the description of Rollkit across various files to emphasize its new positioning as the first sovereign rollup framework, simplifying the launch of customizable blockchains akin to deploying smart contracts.

### CODE REVIEW

**Review by MSevey — DISMISSED** [review]

**Comment by MSevey** [comment]
looks like you need to run the make command to re-gen the CLI docs. 
also update PR title to `chore: update CLI docs description`

**Review by tuxcanfly — APPROVED** [review]
OK.

**Review by yarikbratashchuk — APPROVED** [review]
Looks good.

I was thinking that we compare actions:  "as easily as **deploying** a smart contract." would

**Comment by Manav-Aggarwal** [comment]
> Looks good.
> 
> I was thinking that we compare actions: "as easily as **deploying** a smart contract."

Just making it consistent with the positioning on website. I think we can revisit adding the word `deploying` in the future though,

**Pull request merged**
