### PR TITLE
Update workflow to point back at rollmint

### PR DESCRIPTION
**Pull request by joroshiba**
## Overview

Moving the build to use the main of celestiaorg/ethermint which has been upgraded to a newer version of ethermint and uses rollmint instead of optimism as it should.

### CODE REVIEW

**Review by tzdybal — APPROVED** [review]
LGTM

**Review by jbowen93 — CHANGES_REQUESTED** [review]
While this LGTM I'd like to take the opportunity to modify a few things in the docker workflow.

1. We should remove the testing phase until we're in a more settled place with the ephemeral-cluster
2. We shouldn't build `arm64` images as that will take ~30 minutes 
3. Because of (1) we should rename this file to just `docker-build-ethermint.yml`
4. The triggers should be modified so we know this is working in a PR

Overall we should try to bring this GH action closer to the changes made in celestia-node [here](https://github.com/celestiaorg/celestia-node/blob/main/.github/workflows/docker-build.yml)

**Comment by tzdybal** [comment]
> 4\. The triggers should be modified so we know this is working in a PR

I think jobs are skipped because this PR is from fork, and we disabled them because of credentials / permissions.

**Review by Manav-Aggarwal — APPROVED** [review]

**Comment by joroshiba** [comment]
I've updated these to be a closer match to the `celestia-node` builds.

**Review by Manav-Aggarwal — APPROVED** [review]

**Comment by nashqueue** [comment]
Is this issue still relevant after https://github.com/celestiaorg/ephemeral-cluster/pull/33

**Comment by joroshiba** [comment]
> @joroshiba Is this issue still relevant after [celestiaorg/ephemeral-cluster#33](https://github.com/celestiaorg/ephemeral-cluster/pull/33)

Yes. This is updating to use a more up-to-date version of the Ethermint fork which uses cosmos v0.46.3, while existing fork uses v0.45.5.

The ephemeral cluster updates were more about the usability of the ephemeral cluster.

**Comment by Manav-Aggarwal** [comment]
Stale PR since https://github.com/celestiaorg/ephemeral-cluster is archived.

**Pull request closed without merging**
