### PR TITLE
feat: implemented headerbyhash

### PR DESCRIPTION
**Pull request by chandiniv1**
closes: #356

### CODE REVIEW

**Comment by MSevey** [comment]
Thanks for the PR!
Looks like the linter is failing, should be a quick formatting fix.

Also can you please add a unit test for the new funciton?

Thanks!

**Comment by nashqueue** [comment]
Thank you for your contribution. This is an old issue and we need to follow up and see if this is still applicable. Is this something you are working on that requires it?

**Comment by gupadhyaya** [comment]
looks like, its already implemented in https://github.com/rollkit/rollkit/blob/main/node/full_client.go#L804
we can close this PR.

**Comment by chandiniv1** [comment]
> 



> Thank you for your contribution. This is an old issue and we need to follow up and see if this is still applicable. Is this something you are working on that requires it?

No @nashqueue I'd like to join the effort by starting with this issue

**Pull request closed without merging**
